[package]
name = "goonpass"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.2"
egui_extras = { version = "0.32.2", features = ["svg"] }
rand = "0.9.2"

[build-dependencies]
cc = "1.2.36"
